# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stock_Search(object):
    def setupUi(self, Stock_Search):
        Stock_Search.setObjectName("Stock_Search")
        Stock_Search.resize(990, 797)
        self.background = QtWidgets.QLabel(Stock_Search)
        self.background.setGeometry(QtCore.QRect(0, 0, 991, 801))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.logo = QtWidgets.QLabel(Stock_Search)
        self.logo.setGeometry(QtCore.QRect(850, 0, 141, 121))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.pushButton = QtWidgets.QPushButton(Stock_Search)
        self.pushButton.setGeometry(QtCore.QRect(20, 0, 291, 331))
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.bull = QtWidgets.QLabel(Stock_Search)
        self.bull.setGeometry(QtCore.QRect(-10, -10, 361, 371))
        self.bull.setText("")
        self.bull.setPixmap(QtGui.QPixmap("bull.png"))
        self.bull.setScaledContents(True)
        self.bull.setObjectName("bull")
        self.output = QtWidgets.QLabel(Stock_Search)
        self.output.setGeometry(QtCore.QRect(20, 420, 961, 371))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(232, 230, 255);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.output.setText("")
        self.output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.output.setObjectName("output")
        self.save = QtWidgets.QPushButton(Stock_Search)
        self.save.setGeometry(QtCore.QRect(570, 140, 251, 81))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(28)
        self.save.setFont(font)
        self.save.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(232, 230, 255);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(Stock_Search)
        self.load.setGeometry(QtCore.QRect(670, 230, 251, 81))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(28)
        self.load.setFont(font)
        self.load.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(232, 230, 255);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.load.setObjectName("load")
        self.input = QtWidgets.QLineEdit(Stock_Search)
        self.input.setGeometry(QtCore.QRect(20, 360, 401, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.input.setFont(font)
        self.input.setText("")
        self.input.setFrame(True)
        self.input.setAlignment(QtCore.Qt.AlignCenter)
        self.input.setObjectName("input")
        self.combox = QtWidgets.QComboBox(Stock_Search)
        self.combox.setGeometry(QtCore.QRect(470, 50, 251, 81))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.combox.setFont(font)
        self.combox.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(232, 230, 255);\n"
"")
        self.combox.setMaxVisibleItems(10)
        self.combox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combox.setObjectName("combox")
        self.combox.addItem("")
        self.readme = QtWidgets.QPushButton(Stock_Search)
        self.readme.setGeometry(QtCore.QRect(430, 360, 101, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(12)
        self.readme.setFont(font)
        self.readme.setObjectName("readme")
        self.TIME_TIME = QtWidgets.QLabel(Stock_Search)
        self.TIME_TIME.setGeometry(QtCore.QRect(540, 360, 441, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(16)
        self.TIME_TIME.setFont(font)
        self.TIME_TIME.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(232, 230, 255);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.TIME_TIME.setText("")
        self.TIME_TIME.setAlignment(QtCore.Qt.AlignCenter)
        self.TIME_TIME.setObjectName("TIME_TIME")
        self.background.raise_()
        self.logo.raise_()
        self.bull.raise_()
        self.output.raise_()
        self.save.raise_()
        self.load.raise_()
        self.input.raise_()
        self.combox.raise_()
        self.pushButton.raise_()
        self.readme.raise_()
        self.TIME_TIME.raise_()

        self.retranslateUi(Stock_Search)
        self.combox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Stock_Search)

    def retranslateUi(self, Stock_Search):
        _translate = QtCore.QCoreApplication.translate
        Stock_Search.setWindowTitle(_translate("Stock_Search", "Stock_Search"))
        self.save.setText(_translate("Stock_Search", "存檔"))
        self.load.setText(_translate("Stock_Search", "讀檔"))
        self.combox.setCurrentText(_translate("Stock_Search", "上市上櫃公司清單"))
        self.combox.setItemText(0, _translate("Stock_Search", "上市上櫃公司清單"))
        self.readme.setText(_translate("Stock_Search", "使用說明"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Stock_Search = QtWidgets.QWidget()
    ui = Ui_Stock_Search()
    ui.setupUi(Stock_Search)
    Stock_Search.show()
    sys.exit(app.exec_())
